//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carriers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Rates
    {
        public int Id { get; set; }
        public int Carrier { get; set; }

        [DisplayName("User")]
        public int User { get; set; }
        public int Rate { get; set; }
    
        public virtual Carriers Carriers { get; set; }
        public virtual Users Users { get; set; }
    }
}
