//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carriers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Rates
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Carrier is required.")]
        public int Carrier { get; set; }

        [Required(ErrorMessage = "User is required.")]
        [DisplayName("User")]
        public int User { get; set; }

        [Required(ErrorMessage = "Rate is required.")]
        [Range(0.01, 9999999.99, ErrorMessage = "The rate must be between 0,01 and 9999999,99.")]
        public decimal Rate { get; set; }
    
        public virtual Carriers Carriers { get; set; }
        public virtual Users Users { get; set; }
    }
}
